### ISSUE TITLE
j5040-itx/booting on legacy boot mode

### ISSUE THREAD

**Issue by bhonza** [pocopico/tinycore-redpill#20]
Is there a way to boot this without using legacy boot mode as my motherboard only supports UEFI?
It boots fine on my thinkpad but I can't seem to make it work on this motherboard.

**Comment by derrickhang** [comment]
I have the same problem,my motherboard only supports UEFI.

**Comment by derrickhang** [comment]
[](https://github.com/ndeineko/grub2-bios-uefi-usb#install-them-using-the-package-manager-for-instance-on-ubuntu-)First of all, on you current installation, check if the folder /usr/lib/grub/ exists and is not empty. If it is empty or does not exist, make sure the package grub-common (or equivalent for your distribution) version 2 or higher is installed. Depending on the system, /usr/lib/grub/ will contain one or more of the following folders: x86_64-efi, x86_64-efi-signed, i386-pc, i386-efi, ...

The x86_64-efi, i386-pc and i386-efi folders need to be present in order to install the corresponding bootloader on the usb drive.

Install them using the package manager, for instance on Ubuntu :
sudo apt install grub-pc-bin grub-efi-ia32-bin grub-efi-amd64-bin

Mount the filesystem:
sudo mount -o umask=000 /dev/sdb1 /mnt
Write the MBR and install the grub files required for legacy BIOS boot on the drive: (i don't know if this step is really needed but anyway it works)
sudo grub-install --no-floppy --boot-directory=/mnt/boot --target=i386-pc /dev/sdb
Install /EFI/BOOT/BOOTX64.EFI and other grub files required to load grub from a 64-bit UEFI firmware:
sudo grub-install --removable --boot-directory=/mnt/boot --efi-directory=/mnt --target=x86_64-efi /dev/sdb
Unmount the filesystem:
sudo umount /dev/sdb1

**Comment by bhonza** [comment]
Thank you, I will try that.

**Comment by pocopico** [comment]
Fix provided
