### ISSUE TITLE
Recover  DSM on bromolow-7.1.0-42661

### ISSUE THREAD

**Issue by dookei** [pocopico/tinycore-redpill#92]
Hi there,
I just installed on a TheCUS N5550
foollowing all the steps. 

```
./rploader.sh serialgen DS3651xs
./rploader.sh usbidentify now
./rploader.sh satamap now
./rploader.sh backup now
./rploader.sh build bromolow-7.1.0-42661
./rploader.sh build bromolow-7.1.0-42661
```

Everything works fine... unti I first start.
Then I get stuck in this page.
![image](https://user-images.githubusercontent.com/24986481/173367651-d308a6d4-004c-454d-a922-171b2882eaed.png)

**Comment by pocopico** [comment]
Do you get the same with ds3622xs ?

**Comment by dookei** [comment]
thanks for the fast reply. 
I just started  the NAS  with one disk only and now is installing the DSM. I am able to install it.
But once I plug in all the disks keeps prompting the recover.
I will try with `./rploader.sh serialgen DS3622xs`

**Comment by dookei** [comment]
Just tried with ./rploader.sh serialgen DS3622xs 
Same here

**Comment by pocopico** [comment]
The recovery issue has to do with the smallupdate that the DSM downloads from syno after the install. You can go back to tinycore and run the ./rploader.sh postupdate bromolow-7.1.0-42661 

for the ds3622xs, it’s not enough to just change the serial. You need to rebuild the loader from scratch. I suggest you move to ds3622xs since as per syno, the ds3615xs will not be updated to future releases.
